-- MySQL Script generated by MySQL Workbench
-- Thu Aug  7 15:03:06 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema abc_corp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema abc_corp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `abc_corp` DEFAULT CHARACTER SET utf8 ;
USE `abc_corp` ;

-- -----------------------------------------------------
-- Table `abc_corp`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abc_corp`.`employee` (
  `employeenumber` INT NOT NULL,
  `attrition` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`employeenumber`),
  UNIQUE INDEX `employeenumber_UNIQUE` (`employeenumber` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abc_corp`.`employee_demographics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abc_corp`.`employee_demographics` (
  `employeenumber` INT NOT NULL,
  `age` INT NULL,
  `gender` VARCHAR(45) NULL,
  `marital_status` VARCHAR(45) NULL,
  `date_birth` DATETIME NULL,
  `generation` VARCHAR(45) NULL,
  `education` VARCHAR(45) NULL,
  `educationfield` VARCHAR(45) NULL,
  `distance_from_home` VARCHAR(45) NULL,
  `employee_employeenumber` INT NOT NULL,
  UNIQUE INDEX `employeenumber_UNIQUE` (`employeenumber` ASC) VISIBLE,
  INDEX `fk_employee_demographics_employee_idx` (`employee_employeenumber` ASC) VISIBLE,
  CONSTRAINT `fk_employee_demographics_employee`
    FOREIGN KEY (`employee_employeenumber`)
    REFERENCES `abc_corp`.`employee` (`employeenumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abc_corp`.`employee_professional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abc_corp`.`employee_professional` (
  `employeenumber` INT NOT NULL,
  `job_role` VARCHAR(100) NULL,
  `departament` VARCHAR(100) NULL,
  `years_at_company` INT NULL,
  `num_companies_worked` INT NULL,
  `over_time` VARCHAR(45) NULL,
  `training_times_last_year` INT NULL,
  `years_in_current_role` INT NULL,
  `job_level` INT NULL,
  `business_travel` VARCHAR(45) NULL,
  `standard_hours` VARCHAR(45) NULL,
  `remote_work` VARCHAR(45) NULL,
  `employee_employeenumber` INT NOT NULL,
  UNIQUE INDEX `employeenumber_UNIQUE` (`employeenumber` ASC) VISIBLE,
  INDEX `fk_employee_professional_employee1_idx` (`employee_employeenumber` ASC) VISIBLE,
  CONSTRAINT `fk_employee_professional_employee1`
    FOREIGN KEY (`employee_employeenumber`)
    REFERENCES `abc_corp`.`employee` (`employeenumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abc_corp`.`employee_financial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abc_corp`.`employee_financial` (
  `employeenumber` INT NOT NULL,
  `monthly_income` DECIMAL(10,2) NULL,
  `monthly_rate` DECIMAL(10,2) NULL,
  `salary` DECIMAL(10,2) NULL,
  `stock_option_level` INT NULL,
  `daily_rate` DECIMAL(8,2) NULL,
  `percent_salary_hike` DECIMAL(5,2) NULL,
  `employee_employeenumber` INT NOT NULL,
  UNIQUE INDEX `employeenumber_UNIQUE` (`employeenumber` ASC) VISIBLE,
  INDEX `fk_employee_financial_employee1_idx` (`employee_employeenumber` ASC) VISIBLE,
  CONSTRAINT `fk_employee_financial_employee1`
    FOREIGN KEY (`employee_employeenumber`)
    REFERENCES `abc_corp`.`employee` (`employeenumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abc_corp`.`employee_satisfaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abc_corp`.`employee_satisfaction` (
  `employeenumber` INT NOT NULL,
  `job_satisfaction` INT NULL,
  `performance_rating` INT NULL,
  `relationship_satisfaction` INT NULL,
  `work_life_balance` INT NULL,
  `environment_satisfaction` INT NULL,
  `job_involvement` INT NULL,
  `employee_employeenumber` INT NOT NULL,
  UNIQUE INDEX `employeenumber_UNIQUE` (`employeenumber` ASC) VISIBLE,
  INDEX `fk_employee_satisfaction_employee1_idx` (`employee_employeenumber` ASC) VISIBLE,
  CONSTRAINT `fk_employee_satisfaction_employee1`
    FOREIGN KEY (`employee_employeenumber`)
    REFERENCES `abc_corp`.`employee` (`employeenumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
